// @generated by bindgen from fpp_analysis v0.0.0 — do not edit
//! Declarative mirror of the `fpp_analysis` semantic layer, expanded by the
//! `fpp_python_macros::fpp_sem_bindings!` proc macro into the read-only PyO3
//! wrappers for the semantic data structures. GENERATED by `bindgen`
//! (rustdoc-JSON reflection of `fpp_analysis`, rooted at `Analysis`) — do not
//! edit by hand; regenerate with
//! `cargo run -p fpp_python_bindgen`.
#![allow(dead_code, unused_variables, clippy::all)]

fpp_python_macros::fpp_sem_bindings! {
    traits {
        fpp_analysis::analyzers::NestedScopeState,
        fpp_analysis::semantics::SymbolInterface,
    }

    analysis native fpp_analysis::Analysis {
        fields {
            input_file_set: skip,
            dependency_file_set: skip,
            direct_dependency_file_set: skip,
            missing_dependency_file_set: skip,
            included_file_set: skip,
            include_context_map: skip,
            location_specifier_map: map(tuple(leaf(crate::ast::SpecLocKind), entity(QualifiedName)), astdef(SpecLoc)),
            dictionary_generation: bool,
            global_scope: entity(Scope),
            parent_symbol_map: map(union(Symbol), union(Symbol)),
            symbol_scope_map: map(union(Symbol), entity(Scope)),
            use_def_map: map(node, union(Symbol)),
            symbol_map: map(node, union(Symbol)),
            type_map: map(node, union(Type)),
            value_map: map(node, union(Value)),
            framework_definitions: entity(FrameworkDefinitions),
            component_map: map(union(Symbol), entity(Component)),
            component_instance_map: map(union(Symbol), rewrap(InterfaceInstance::Component)),
            interface_map: map(union(Symbol), entity(Interface)),
            partial_topology_map: map(union(Symbol), entity(Topology)),
            topology_map: map(union(Symbol), entity(Topology)),
            state_machine_map: map(union(Symbol), entity(StateMachine)),
            dictionary_map: map(union(Symbol), entity(Dictionary)),
            implied_use_map: map(node, entity(ImpliedUseSet)),
            dictionary_symbol_set: list(union(Symbol)),
            system_map: map(union(Symbol), entity(FppSystem)),
        }
        methods {
            check_displayable_params(params: ref list(astnode(FormalParam)), msg: str) throws -> unit,
            check_displayable_type(node: node, loc: span, msg: str) throws -> unit,
            get_array_size(node: node, loc: span) throws -> i128,
            get_array_size_opt(expr: ref opt(astnode(Expr))) throws -> i128,
            get_big_int_value(node: node) -> opt(i128),
            get_big_int_value_opt(expr: ref opt(astnode(Expr))) -> opt(i128),
            get_component(id: node) throws -> opt(entity(Component)),
            get_component_instance(id: node) throws -> opt(rewrap(InterfaceInstance::Component)),
            get_component_instance_symbol(id: node) throws -> opt(union(Symbol)),
            get_dictionary(id: node) throws -> opt(entity(Dictionary)),
            get_enclosing_names(symbol: ref union(Symbol)) -> list(str),
            get_finalized_type(node: node) -> opt(union(Type)),
            get_int_value(node: node) -> opt(i128),
            get_int_value_checked(node: node, loc: span) throws -> i128,
            get_interface(id: node) -> opt(entity(Interface)),
            get_interface_instance(id: node) -> opt(union(InterfaceInstance)),
            get_interface_instance_symbol(id: node) throws -> opt(union(Symbol)),
            get_interface_symbol(id: node) throws -> opt(union(Symbol)),
            get_nonnegative_big_int_value(node: node, loc: span) throws -> i128,
            get_nonnegative_big_int_value_opt(expr: ref opt(astnode(Expr))) throws -> opt(i128),
            get_nonnegative_int_value(node: node, loc: span) throws -> i128,
            get_qualified_name(symbol: ref union(Symbol)) -> str,
            get_reason_for_non_displayable_type_at(node: node) -> list(tuple(span, str)),
            get_scope(symbol: ref opt(union(Symbol))) -> ref entity(Scope),
            get_topology(id: node) throws -> opt(entity(Topology)),
            get_topology_symbol(id: node) throws -> opt(union(Symbol)),
            implied_uses(node: node) -> opt(entity(ImpliedUseSet)),
        }
    }

    union Command native fpp_analysis::semantics::Command handle clone alias "Command" accessor native repr name(get_name) {
        variants {
            NonParam => NonParamCommand : struct { node: astdef(SpecCommand), kind: union(NonParamKind) },
            Param => ParamCommand : struct { node: astdef(SpecParam), kind: leaf(crate::sem::ParamKind) },
        }
        methods {
            get_name -> str,
            is_async -> bool,
        }
    }

    union FormatPart native fpp_analysis::semantics::FormatPart handle clone alias "FormatPart" accessor native {
        variants {
            Literal => LiteralFormatPart : str,
            FormatReplacement => FormatReplacementFormatPart : payload,
        }
    }

    union FormatReplacementKind native fpp_analysis::semantics::FormatReplacementKind handle clone alias "FormatReplacementKind" accessor native {
        variants {
            Default => DefaultFormatReplacementKind : unit,
            Integer => IntegerFormatReplacementKind : leaf(crate::sem::IntegerFormatKind),
            Rational => RationalFormatReplacementKind : struct { precision: opt(usize), kind: leaf(crate::sem::RationalFormatKind) },
        }
    }

    union GeneralKind native fpp_analysis::semantics::GeneralKind handle clone alias "GeneralKind" accessor native {
        variants {
            AsyncInput => AsyncInputGeneralKind : struct { priority: opt(i128), queue_full: leaf(crate::ast::QueueFull) },
            GuardedInput => GuardedInputGeneralKind : unit,
            Output => OutputGeneralKind : unit,
            SyncInput => SyncInputGeneralKind : unit,
        }
    }

    union InterfaceInstance native fpp_analysis::semantics::InterfaceInstance handle clone alias "InterfaceInstance" accessor native repr name(qualified_name) {
        variants {
            Component => ComponentInterfaceInstance : payload,
            Topology => TopologyInterfaceInstance : payload,
        }
        methods {
            as_topology(a: analysis) -> opt(entity(Topology)),
            get_component_instance_opt -> opt(rewrap(InterfaceInstance::Component)),
            get_interface(a: analysis) -> opt(entity(PortInterface)),
            get_port_instance(a: analysis, name: ref astnode(Ident)) throws -> union(PortInstance),
            qualified_name -> str,
            unqualified_name -> str,
        }
    }

    union NonParamKind native fpp_analysis::semantics::NonParamKind handle clone alias "NonParamKind" accessor native {
        variants {
            Async => AsyncNonParamKind : struct { priority: opt(i128), queue_full: leaf(crate::ast::QueueFull) },
            Guarded => GuardedNonParamKind : unit,
            Sync => SyncNonParamKind : unit,
        }
    }

    union PortInstance native fpp_analysis::semantics::PortInstance handle clone alias "PortInstance" accessor native repr display {
        variants {
            General => GeneralPortInstance : payload,
            Special => SpecialPortInstance : payload,
            Internal => InternalPortInstance : payload,
            Topology => TopologyPortInstance : payload,
        }
        methods {
            get_array_size -> i128,
            get_direction -> opt(leaf(crate::sem::Direction)),
            get_import_locs -> list(span),
            get_import_node_ids -> ref list(node),
            get_node_id -> node,
            get_special_kind -> opt(leaf(crate::ast::SpecialPortInstanceKind)),
            get_type -> opt(union(PortInstanceType)),
            get_unqualified_name -> ref str,
            is_async_input -> bool,
            require_connection_at(loc: span) throws -> unit,
            signature_eq(other: ref union(PortInstance)) -> bool,
            with_import_specifier(import_node: node) -> union(PortInstance),
        }
    }

    union PortInstanceType native fpp_analysis::semantics::PortInstanceType handle clone alias "PortInstanceType" accessor native {
        variants {
            DefPort => DefPortPortInstanceType : astdef(DefPort),
            Serial => SerialPortInstanceType : unit,
        }
        methods {
            port_returns_value -> opt(span),
        }
    }

    union StateMachineSymbol native fpp_analysis::semantics::state_machine::StateMachineSymbol handle clone alias "StateMachineSymbol" accessor native loc_from_node repr name(get_unqualified_name) {
        variants {
            Action => StateMachineSymbolAction : astdef(DefAction),
            Guard => StateMachineSymbolGuard : astdef(DefGuard),
            Choice => StateMachineSymbolChoice : astdef(DefChoice),
            Signal => StateMachineSymbolSignal : astdef(DefSignal),
            State => StateMachineSymbolState : astdef(DefState),
        }
        methods {
            get_unqualified_name -> ref str,
            node -> node,
        }
    }

    union StateMachineTypedElement native fpp_analysis::semantics::state_machine::StateMachineTypedElement handle clone alias "StateMachineTypedElement" accessor native {
        variants {
            StateEntry => StateEntryStateMachineTypedElement : astdef(SpecStateEntry),
            StateExit => StateExitStateMachineTypedElement : astdef(SpecStateExit),
            InitialTransition => InitialTransitionStateMachineTypedElement : astdef(SpecInitialTransition),
            StateTransition => StateTransitionStateMachineTypedElement : astdef(SpecStateTransition),
            Choice => ChoiceStateMachineTypedElement : astdef(DefChoice),
        }
        methods {
            get_node_id -> node,
            show_kind -> ref str,
        }
    }

    union StateOrChoice native fpp_analysis::semantics::state_machine::StateOrChoice handle clone alias "StateOrChoice" accessor native repr name(get_name) {
        variants {
            State => StateStateOrChoice : union(StateMachineSymbol),
            Choice => ChoiceStateOrChoice : union(StateMachineSymbol),
        }
        methods {
            get_name -> str,
            get_symbol -> ref union(StateMachineSymbol),
        }
    }

    union Symbol native fpp_analysis::semantics::Symbol handle symbol alias "Symbol" accessor sym identity node repr analysis_name(get_qualified_name) {
        variants {
            AbsType => SymbolAbsType : astdef(DefAbsType),
            AliasType => SymbolAliasType : astdef(DefAliasType),
            ArrayType => SymbolArrayType : astdef(DefArray),
            Component => SymbolComponent : astdef(DefComponent),
            ComponentInstance => SymbolComponentInstance : astdef(DefComponentInstance),
            Constant => SymbolConstant : astdef(DefConstant),
            EnumType => SymbolEnumType : astdef(DefEnum),
            EnumConstant => SymbolEnumConstant : astdef(DefEnumConstant),
            Interface => SymbolInterface : astdef(DefInterface),
            Module => SymbolModule : astdef(DefModule),
            Port => SymbolPort : astdef(DefPort),
            StateMachine => SymbolStateMachine : astdef(DefStateMachine),
            StructType => SymbolStructType : astdef(DefStruct),
            System => SymbolSystem : astdef(DefSystem),
            Topology => SymbolTopology : astdef(DefTopology),
        }
        methods {
            is_dictionary_def -> bool,
            node -> node,
            parent(a: analysis) -> opt(union(Symbol)),
            qualified_name(a: analysis) -> str,
            unqualified_name -> ref str,
        }
    }

    union Transition native fpp_analysis::semantics::state_machine::Transition handle clone alias "Transition" accessor native {
        variants {
            External => ExternalTransition : struct { actions: list(union(StateMachineSymbol)), target: union(StateOrChoice) },
            Internal => InternalTransition : struct { actions: list(union(StateMachineSymbol)) },
        }
        methods {
            get_actions -> ref list(union(StateMachineSymbol)),
            get_target_opt -> opt(union(StateOrChoice)),
        }
    }

    union TransitionGraphArc native fpp_analysis::semantics::transition_graph::Arc handle clone alias "TransitionGraphArc" accessor native {
        variants {
            Initial => InitialTransitionGraphArc : struct { start_state: union(StateMachineSymbol), a_node: astdef(SpecInitialTransition), end_node: entity(TransitionGraphNode) },
            State => StateTransitionGraphArc : struct { start_state: union(StateMachineSymbol), a_node: astdef(SpecStateTransition), end_node: entity(TransitionGraphNode) },
            Choice => ChoiceTransitionGraphArc : struct { start_choice: union(StateMachineSymbol), a_node: astdef(TransitionExpr), end_node: entity(TransitionGraphNode) },
        }
        methods {
            get_end_node -> ref entity(TransitionGraphNode),
            get_start_node -> entity(TransitionGraphNode),
            get_typed_element -> union(StateMachineTypedElement),
            show_kind -> ref str,
            show_transition -> str,
        }
    }

    union Type native fpp_analysis::semantics::Type handle arc_type alias "Type" accessor ty include_base custom_build identity identical(identical, def_node_id) repr display {
        variants {
            PrimitiveInt => PrimitiveIntType : leaf(crate::ast::IntegerKind),
            Float => FloatType : leaf(crate::ast::FloatKind),
            String => StringType : opt(i128),
            Boolean => BooleanType : unit,
            Integer => IntegerType : unit,
            Abs => AbsType : payload,
            Alias => AliasType : payload,
            Array => ArrayType : payload,
            AnonArray => AnonArrayType : payload,
            Enum => EnumType : payload,
            Struct => StructType : payload,
            AnonStruct => AnonStructType : payload,
        }
        methods {
            array_size -> opt(usize),
            as_anon_array -> opt(rewrap(Type::AnonArray)),
            as_anon_struct -> opt(rewrap(Type::AnonStruct)),
            assoc common_type(t2_a: ref arc(union(Type))) -> opt(union(Type)),
            assoc convert(to: ref arc(union(Type))) throws -> unit,
            def_node_id -> opt(node),
            def_symbol -> opt(union(Symbol)),
            default_value -> opt(union(Value)),
            has_numeric_members -> bool,
            assoc identical(t2: ref union(Type)) -> bool,
            is_canonical -> bool,
            is_convertible_to_numeric -> bool,
            is_displayable -> bool,
            is_float -> bool,
            is_int -> bool,
            is_numeric -> bool,
            is_primitive -> bool,
            is_promotable_to_array -> bool,
            is_promotable_to_struct -> bool,
            primitive_serialized_size -> opt(i128),
            serialized_size(a: analysis) throws -> i128,
            assoc underlying_type -> union(Type),
        }
    }

    union Value native fpp_analysis::semantics::Value handle value alias "Value" accessor val repr display {
        variants {
            PrimitiveInteger => PrimitiveIntegerValue : payload,
            AbsType => AbsTypeValue : payload,
            Integer => IntegerValue : newtype(i128),
            Float => FloatValue : payload,
            Boolean => BooleanValue : newtype(bool),
            String => StringValue : newtype(str),
            EnumConstant => EnumConstantValue : payload,
            AnonArray => AnonArrayValue : payload,
            Array => ArrayValue : payload,
            AnonStruct => AnonStructValue : payload,
            Struct => StructValue : payload,
        }
        methods {
            add(other: ref union(Value)) throws -> union(Value),
            as_shift_int -> opt(i128),
            convert(ty_a: ref arc(union(Type))) -> opt(union(Value)),
            div(other: ref union(Value)) throws -> union(Value),
            get_type -> union(Type),
            is_zero -> bool,
            mul(other: ref union(Value)) throws -> union(Value),
            negate throws -> union(Value),
            shl(other: ref union(Value)) throws -> union(Value),
            shr(other: ref union(Value)) throws -> union(Value),
            sub(other: ref union(Value)) throws -> union(Value),
            truncate -> union(Value),
        }
    }

    payload AbsType native fpp_analysis::semantics::AbsType {
        fields {
            node: astdef(DefAbsType),
        }
    }

    payload AbsTypeValue native fpp_analysis::semantics::AbsTypeValue {
        fields {
            ty: rewrap(Type::Abs),
        }
    }

    payload AliasType native fpp_analysis::semantics::AliasType {
        fields {
            node: astdef(DefAliasType),
            alias_type: union(Type),
        }
    }

    payload AnonArrayType native fpp_analysis::semantics::AnonArrayType {
        fields {
            size: opt(usize),
            elt_type: union(Type),
        }
    }

    payload AnonArrayValue native fpp_analysis::semantics::AnonArrayValue {
        fields {
            elements: list(union(Value)),
            scalar: opt(union(Value)),
        }
        methods {
            get(index: usize) -> opt(union(Value)),
        }
    }

    payload AnonStructType native fpp_analysis::semantics::AnonStructType {
        fields {
            members: list(tuple(str, union(Type))),
        }
        methods {
            get_member(name: str) -> opt(union(Type)),
            has_member(name: str) -> bool,
        }
    }

    payload AnonStructValue native fpp_analysis::semantics::AnonStructValue {
        fields {
            members: map(str, union(Value)),
        }
    }

    payload ArrayType native fpp_analysis::semantics::ArrayType {
        fields {
            node: astdef(DefArray),
            anon_array: rewrap(Type::AnonArray),
            default: opt(rewrap(Value::Array)),
            format: opt(entity(Format)),
        }
    }

    payload ArrayValue native fpp_analysis::semantics::ArrayValue {
        fields {
            anon_array: rewrap(Value::AnonArray),
            ty: rewrap(Type::Array),
        }
    }

    payload ComponentInterfaceInstance native fpp_analysis::semantics::ComponentInstance {
        fields {
            node: astdef(DefComponentInstance),
            qualified_name: str,
            component_symbol: union(Symbol),
            base_id: i128,
            max_id: i128,
            file: opt(str),
            queue_size: opt(i128),
            stack_size: opt(i128),
            priority: opt(i128),
            cpu: opt(i128),
            init_specifier_map: map(i128, entity(InitSpecifier)),
        }
        methods {
            add_init_specifier(spec: entity(InitSpecifier)) throws -> rewrap(InterfaceInstance::Component),
            get_component(a: analysis) -> opt(entity(Component)),
            get_interface(a: analysis) -> opt(entity(PortInterface)),
            get_qualified_name -> ref str,
            get_unqualified_name -> ref str,
        }
    }

    payload EnumConstantValue native fpp_analysis::semantics::EnumConstantValue {
        fields {
            value: tuple(str, i128),
            ty: rewrap(Type::Enum),
        }
    }

    payload EnumType native fpp_analysis::semantics::EnumType {
        fields {
            node: astdef(DefEnum),
            rep_type: leaf(crate::ast::IntegerKind),
            default: opt(rewrap(Value::EnumConstant)),
        }
    }

    payload FloatValue native fpp_analysis::semantics::FloatValue {
        fields {
            value: f64,
            kind: leaf(crate::ast::FloatKind),
        }
    }

    payload FormatReplacementFormatPart native fpp_analysis::semantics::FormatReplacementField {
        fields {
            span: span,
            kind: union(FormatReplacementKind),
        }
    }

    payload GeneralPortInstance native fpp_analysis::semantics::GeneralPortInstance {
        fields {
            node: astdef(SpecGeneralPortInstance),
            kind: union(GeneralKind),
            size: i128,
            ty: union(PortInstanceType),
            import_node_ids: list(node),
        }
        methods {
            get_array_size -> i128,
            get_direction -> leaf(crate::sem::Direction),
            get_import_locs -> list(span),
            get_import_node_ids -> ref list(node),
            get_node_id -> node,
            get_type -> union(PortInstanceType),
            get_unqualified_name -> ref str,
            is_async_input -> bool,
            with_import_specifier(import_node: node) -> rewrap(PortInstance::General),
        }
    }

    payload InternalPortInstance native fpp_analysis::semantics::InternalPortInstance {
        fields {
            node: astdef(SpecInternalPort),
            priority: opt(i128),
            queue_full: leaf(crate::ast::QueueFull),
        }
        methods {
            get_node_id -> node,
            get_unqualified_name -> ref str,
        }
    }

    payload PrimitiveIntegerValue native fpp_analysis::semantics::PrimitiveIntegerValue {
        fields {
            value: i128,
            kind: leaf(crate::ast::IntegerKind),
        }
    }

    payload SpecialPortInstance native fpp_analysis::semantics::SpecialPortInstance {
        fields {
            node: astdef(SpecSpecialPortInstance),
            def: astdef(DefPort),
            priority: opt(i128),
            queue_full: opt(leaf(crate::ast::QueueFull)),
            import_node_ids: list(node),
        }
        methods {
            get_direction -> leaf(crate::sem::Direction),
            get_import_locs -> list(span),
            get_import_node_ids -> ref list(node),
            get_node_id -> node,
            get_special_kind -> leaf(crate::ast::SpecialPortInstanceKind),
            get_type -> union(PortInstanceType),
            get_unqualified_name -> ref str,
            is_async_input -> bool,
            with_import_specifier(import_node: node) -> rewrap(PortInstance::Special),
        }
    }

    payload StructType native fpp_analysis::semantics::StructType {
        fields {
            node: astdef(DefStruct),
            anon_struct: rewrap(Type::AnonStruct),
            default: opt(rewrap(Value::Struct)),
            sizes: map(str, usize),
            formats: map(str, entity(Format)),
        }
    }

    payload StructValue native fpp_analysis::semantics::StructValue {
        fields {
            anon_struct: rewrap(Value::AnonStruct),
            ty: rewrap(Type::Struct),
        }
    }

    payload TopologyInterfaceInstance native fpp_analysis::semantics::TopologyInstance {
        fields {
            symbol: union(Symbol),
            qualified_name: str,
        }
    }

    payload TopologyPortInstance native fpp_analysis::semantics::TopologyPortInstance {
        fields {
            node: astdef(SpecTopPort),
            underlying_port: union(PortInstance),
        }
        methods {
            get_node_id -> node,
            get_unqualified_name -> ref str,
        }
    }

    entity CommandEntry native fpp_analysis::semantics::CommandEntry {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            command: union(Command),
        }
    }

    entity Component native fpp_analysis::semantics::Component repr symbol_name(symbol, get_qualified_name) {
        fields {
            symbol: union(Symbol),
            node: astdef(DefComponent),
            port_interface: entity(PortInterface),
            command_map: map(i128, union(Command)),
            default_opcode: i128,
            tlm_channel_map: map(i128, entity(TlmChannel)),
            tlm_channel_name_map: map(str, entity(TlmChannel)),
            default_tlm_channel_id: i128,
            event_map: map(i128, entity(Event)),
            default_event_id: i128,
            param_map: map(i128, entity(Param)),
            default_param_id: i128,
            container_map: map(i128, entity(Container)),
            default_container_id: i128,
            record_map: map(i128, entity(Record)),
            default_record_id: i128,
            state_machine_instance_map: map(str, entity(StateMachineInstance)),
            spec_port_matching_list: list(astdef(SpecPortMatching)),
            port_matching_list: list(entity(PortMatching)),
        }
        methods {
            get_max_id -> i128,
            get_tlm_channel_by_name(name: ref astnode(Ident)) throws -> entity(TlmChannel),
            has_commands -> bool,
            has_data_products -> bool,
            has_events -> bool,
            has_external_parameters -> bool,
            has_parameters -> bool,
            has_state_machine_instances -> bool,
            has_telemetry -> bool,
            port_map -> ref map(str, union(PortInstance)),
            special_port_map -> ref map(leaf(crate::ast::SpecialPortInstanceKind), rewrap(PortInstance::Special)),
        }
    }

    entity Connection native fpp_analysis::semantics::Connection {
        fields {
            from: entity(Endpoint),
            to: entity(Endpoint),
            is_unmatched: bool,
        }
        methods {
            get_other_endpoint(pi: ref union(PortInstance)) -> ref entity(Endpoint),
            get_this_endpoint(pi: ref union(PortInstance)) -> ref entity(Endpoint),
        }
    }

    entity ConnectionPattern native fpp_analysis::semantics::ConnectionPattern {
        fields {
            node: astdef(SpecPatternConnectionGraph),
            source: tuple(rewrap(InterfaceInstance::Component), span),
            targets: list(tuple(rewrap(InterfaceInstance::Component), span)),
        }
        methods {
            kind -> ref leaf(crate::ast::ConnectionPatternKind),
        }
    }

    entity Container native fpp_analysis::semantics::Container repr name(get_name) {
        fields {
            node: astdef(SpecContainer),
            default_priority: opt(i128),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity ContainerEntry native fpp_analysis::semantics::ContainerEntry {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            container: entity(Container),
        }
    }

    entity Dictionary native fpp_analysis::semantics::Dictionary {
        fields {
            used_symbol_set: list(union(Symbol)),
            command_entry_map: map(i128, entity(CommandEntry)),
            tlm_channel_entry_map: map(i128, entity(TlmChannelEntry)),
            reverse_tlm_channel_entry_map: map(entity(TlmChannelEntry), i128),
            event_entry_map: map(i128, entity(EventEntry)),
            param_entry_map: map(i128, entity(ParamEntry)),
            record_entry_map: map(i128, entity(RecordEntry)),
            container_entry_map: map(i128, entity(ContainerEntry)),
            tlm_packet_set_map: map(str, entity(TlmPacketSet)),
        }
        methods {
            find_numeric_id_for_channel(t: ref entity(Topology), channel_id: ref entity(TlmChannelIdentifier)) throws -> i128,
        }
    }

    entity Endpoint native fpp_analysis::semantics::Endpoint {
        fields {
            loc: span,
            port: entity(PortInstanceIdentifier),
            port_number: opt(i128),
            topology_port: opt(entity(Endpoint)),
        }
        methods {
            get_underlying_endpoint(a: analysis) -> entity(Endpoint),
        }
    }

    entity Event native fpp_analysis::semantics::Event repr name(get_name) {
        fields {
            node: astdef(SpecEvent),
            format: entity(Format),
            throttle: opt(entity(Throttle)),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity EventEntry native fpp_analysis::semantics::EventEntry {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            event: entity(Event),
        }
    }

    entity Format native fpp_analysis::semantics::Format {
        methods {
            get(n: usize) -> opt(rewrap(FormatPart::FormatReplacement)),
            is_empty -> bool,
            len -> usize,
        }
    }

    entity FppSystem native fpp_analysis::semantics::FppSystem repr name(get_name) {
        fields {
            node: astdef(DefSystem),
            topology: entity(Topology),
            dictionary: entity(Dictionary),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity FrameworkDefinitions native fpp_analysis::semantics::FrameworkDefinitions {
        fields {
            constant_map: map(str, union(Symbol)),
            type_map: map(str, union(Symbol)),
        }
    }

    entity GuardedTransition native fpp_analysis::semantics::state_machine::GuardedTransition {
        fields {
            guard_opt: opt(union(StateMachineSymbol)),
            transition: union(Transition),
        }
    }

    entity ImpliedUse native fpp_analysis::semantics::ImpliedUse {
        methods {
            annotations -> ref list(str),
            id -> node,
            name -> ref entity(QualifiedName),
        }
    }

    entity ImpliedUseSet native fpp_analysis::semantics::ImpliedUseSet {
        fields {
            constants: list(entity(ImpliedUse)),
            ports: list(entity(ImpliedUse)),
            types: list(entity(ImpliedUse)),
        }
    }

    entity InitSpecifier native fpp_analysis::semantics::InitSpecifier {
        fields {
            node: astdef(SpecInit),
            phase: i128,
        }
    }

    entity Interface native fpp_analysis::semantics::Interface repr name(get_unqualified_name) {
        fields {
            node: astdef(DefInterface),
            import_map: map(union(Symbol), tuple(node, span)),
            port_interface: entity(PortInterface),
        }
        methods {
            add_imported_interface_symbol(symbol: union(Symbol), import: ref astnode(SpecInterfaceImport)) throws -> entity(Interface),
            add_port_instance(instance: union(PortInstance)) throws -> entity(Interface),
            get_unqualified_name -> ref str,
            imports_in_source_order -> list(tuple(union(Symbol), node)),
        }
    }

    entity Param native fpp_analysis::semantics::Param repr name(get_name) {
        fields {
            node: astdef(SpecParam),
            param_type: union(Type),
            default: opt(union(Value)),
            set_opcode: i128,
            save_opcode: i128,
            is_external: bool,
        }
        methods {
            get_name -> ref str,
        }
    }

    entity ParamEntry native fpp_analysis::semantics::ParamEntry {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            param: entity(Param),
        }
    }

    entity PortInstanceIdentifier native fpp_analysis::semantics::PortInstanceIdentifier identity qualified_name(qualified_name) repr name(qualified_name) {
        fields {
            interface_instance: union(InterfaceInstance),
            port_instance: union(PortInstance),
        }
        methods {
            get_unqualified_name -> str,
            qualified_name -> str,
        }
    }

    entity PortInterface native fpp_analysis::semantics::PortInterface {
        fields {
            instance_type: str,
            port_map: map(str, union(PortInstance)),
            special_port_map: map(leaf(crate::ast::SpecialPortInstanceKind), rewrap(PortInstance::Special)),
        }
        methods {
            add_imported_interface(interface: ref entity(Interface), import_node: node) throws -> entity(PortInterface),
            add_port_instance(instance: union(PortInstance)) throws -> entity(PortInterface),
            get_port_instance(name: str, loc: span, interface_name: str) throws -> union(PortInstance),
            implements(other: ref entity(PortInterface)) throws -> unit,
        }
    }

    entity PortMatching native fpp_analysis::semantics::PortMatching repr display {
        fields {
            node: astdef(SpecPortMatching),
            instance1: rewrap(PortInstance::General),
            instance2: rewrap(PortInstance::General),
        }
        methods {
            matches(pi: ref union(PortInstance)) -> bool,
        }
    }

    entity QualifiedName native fpp_analysis::semantics::QualifiedName repr display {
        methods {
            base -> ref str,
            qualifier -> ref list(str),
            short_name(enclosing_names: ref list(string)) -> entity(QualifiedName),
            to_ident_list -> list(str),
        }
    }

    entity Record native fpp_analysis::semantics::Record repr name(get_name) {
        fields {
            node: astdef(SpecRecord),
            record_type: union(Type),
            is_array: bool,
        }
        methods {
            get_name -> ref str,
        }
    }

    entity RecordEntry native fpp_analysis::semantics::RecordEntry {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            record: entity(Record),
        }
    }

    entity Scope native fpp_analysis::semantics::Scope {
    }

    entity StateMachine native fpp_analysis::semantics::StateMachine {
        fields {
            node: astdef(DefStateMachine),
            sma: entity(StateMachineAnalysis),
            actions: list(union(StateMachineSymbol)),
            guards: list(union(StateMachineSymbol)),
            signals: list(union(StateMachineSymbol)),
        }
        methods {
            blocking_error -> bool,
            get_kind -> leaf(crate::sem::Kind),
            get_symbol -> union(Symbol),
            has_actions -> bool,
            has_guards -> bool,
            has_signals -> bool,
            leaf_state_names -> list(str),
        }
    }

    entity StateMachineAnalysis native fpp_analysis::semantics::state_machine::StateMachineAnalysis repr symbol_name(symbol, get_qualified_name) {
        fields {
            symbol: union(Symbol),
            scope_name_list: list(str),
            nested_scope: entity(StateMachineNestedScope),
            parent_state: opt(union(StateMachineSymbol)),
            parent_state_map: map(union(StateMachineSymbol), union(StateMachineSymbol)),
            symbol_scope_map: map(union(StateMachineSymbol), entity(StateMachineScope)),
            use_def_map: map(node, union(StateMachineSymbol)),
            transition_graph: entity(TransitionGraph),
            reverse_transition_graph: entity(TransitionGraph),
            type_option_map: map(union(StateMachineTypedElement), opt(union(Type))),
            signal_transition_map: map(union(StateMachineSymbol), entity(GuardedTransition)),
            flattened_state_transition_map: map(union(StateMachineSymbol), map(union(StateMachineSymbol), entity(GuardedTransition))),
            flattened_choice_transition_map: map(node, union(Transition)),
            blocking_error: bool,
        }
        methods {
            common_type_at_choice(te: ref union(StateMachineTypedElement), te1: ref union(StateMachineTypedElement), to1: ref opt(arc(union(Type))), te2: ref union(StateMachineTypedElement)) -> opt(union(Type)),
            convert_type_options_at_call_site(loc: span, te_kind: str, te_to: ref opt(arc(union(Type))), site_kind: str, site_to: ref opt(arc(union(Type)))) -> opt(union(Type)),
            get_action_symbol(action: ref astnode(Ident)) -> union(StateMachineSymbol),
            get_guard_symbol(guard: ref astnode(Ident)) -> union(StateMachineSymbol),
            get_parent_state_list(s: ref union(StateMachineSymbol), start: list(union(StateMachineSymbol))) -> list(union(StateMachineSymbol)),
            get_qualified_name(symbol: ref union(StateMachineSymbol)) -> str,
            get_signal_symbol(signal: ref astnode(Ident)) -> union(StateMachineSymbol),
        }
    }

    entity StateMachineInstance native fpp_analysis::semantics::StateMachineInstance repr name(get_name) {
        fields {
            node: astdef(SpecStateMachineInstance),
            state_machine: astdef(DefStateMachine),
            priority: opt(i128),
            queue_full: leaf(crate::ast::QueueFull),
        }
        methods {
            get_name -> ref str,
            get_node_id -> node,
            get_sm_kind -> leaf(crate::sem::Kind),
            symbol -> union(Symbol),
        }
    }

    entity StateMachineNestedScope native fpp_analysis::semantics::state_machine::StateMachineNestedScope {
        methods {
            inner_scope -> ref entity(StateMachineScope),
        }
    }

    entity StateMachineScope native fpp_analysis::semantics::state_machine::StateMachineScope {
    }

    entity Throttle native fpp_analysis::semantics::Throttle {
        fields {
            count: usize,
            every: opt(entity(TimeInterval)),
        }
    }

    entity TimeInterval native fpp_analysis::semantics::TimeInterval {
        fields {
            seconds: usize,
            useconds: usize,
        }
    }

    entity TlmChannel native fpp_analysis::semantics::TlmChannel repr name(get_name) {
        fields {
            node: astdef(SpecTlmChannel),
            channel_type: union(Type),
            update: leaf(crate::ast::TlmChannelUpdate),
            format: opt(entity(Format)),
            low_limits: map(leaf(crate::ast::TlmChannelLimitKind), tuple(node, union(Value))),
            high_limits: map(leaf(crate::ast::TlmChannelLimitKind), tuple(node, union(Value))),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity TlmChannelEntry native fpp_analysis::semantics::TlmChannelEntry repr name(get_qualified_name) {
        fields {
            instance: rewrap(InterfaceInstance::Component),
            tlm_channel: entity(TlmChannel),
        }
        methods {
            get_qualified_name -> str,
        }
    }

    entity TlmChannelIdentifier native fpp_analysis::semantics::TlmChannelIdentifier repr display {
        fields {
            node: skip,
            component_instance: rewrap(InterfaceInstance::Component),
            tlm_channel: entity(TlmChannel),
        }
        methods {
            get_qualified_name -> str,
            get_unqualified_name -> str,
        }
    }

    entity TlmPacket native fpp_analysis::semantics::TlmPacket repr name(get_name) {
        fields {
            node: astdef(SpecTlmPacket),
            group: usize,
            member_id_list: list(i128),
            member_location_map: map(i128, span),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity TlmPacketSet native fpp_analysis::semantics::TlmPacketSet repr name(get_name) {
        fields {
            node: astdef(SpecTlmPacketSet),
            packet_map: map(i128, entity(TlmPacket)),
            default_packet_id: i128,
            omitted_id_set: list(i128),
            omitted_location_map: map(i128, span),
        }
        methods {
            get_name -> ref str,
            get_used_id_location_map -> map(i128, span),
            get_used_id_set -> list(i128),
        }
    }

    entity Topology native fpp_analysis::semantics::Topology repr name(unqualified_name) {
        fields {
            symbol: union(Symbol),
            qualified_name: str,
            direct_component_instances: map(union(Symbol), span),
            direct_topologies: map(union(Symbol), span),
            transitive_import_set: list(union(Symbol)),
            instance_map: map(union(InterfaceInstance), span),
            ports: list(astdef(SpecTopPort)),
            raw_direct_graphs: list(astdef(SpecDirectConnectionGraph)),
            raw_patterns: list(astdef(SpecPatternConnectionGraph)),
            port_map: map(str, entity(TopologyPort)),
            port_interface: entity(PortInterface),
            pattern_map: map(leaf(crate::ast::ConnectionPatternKind), entity(ConnectionPattern)),
            connection_map: map(str, list(entity(Connection))),
            local_connection_map: map(str, list(entity(Connection))),
            output_connection_map: map(entity(PortInstanceIdentifier), list(entity(Connection))),
            input_connection_map: map(entity(PortInstanceIdentifier), list(entity(Connection))),
            from_port_number_map: map(entity(Connection), i128),
            to_port_number_map: map(entity(Connection), i128),
            unconnected_port_set: list(entity(PortInstanceIdentifier)),
        }
        methods {
            component_instance_map -> map(rewrap(InterfaceInstance::Component), span),
            connection_exists_between(from: ref entity(PortInstanceIdentifier), to: ref entity(PortInstanceIdentifier)) -> bool,
            get_connections_at(pii: ref entity(PortInstanceIdentifier)) -> list(entity(Connection)),
            get_connections_between(from: ref entity(PortInstanceIdentifier), to: ref entity(PortInstanceIdentifier)) -> list(entity(Connection)),
            get_connections_from(from: ref entity(PortInstanceIdentifier)) -> list(entity(Connection)),
            get_connections_to(to: ref entity(PortInstanceIdentifier)) -> list(entity(Connection)),
            get_name -> ref str,
            get_port_number(pi: ref union(PortInstance), c: ref entity(Connection)) -> opt(i128),
            get_used_port_numbers(pi: ref union(PortInstance), cs: ref list(entity(Connection))) -> list(i128),
            look_up_instance_at(instance: ref union(InterfaceInstance), loc: span) throws -> unit,
            node -> ref astdef(DefTopology),
            resolve_numbers(c: ref entity(Connection)) -> entity(Connection),
            sort_connections(connections: ref list(entity(Connection))) -> list(entity(Connection)),
            unqualified_name -> str,
        }
    }

    entity TopologyPort native fpp_analysis::semantics::TopologyPort repr name(get_name) {
        fields {
            node: astdef(SpecTopPort),
            pii: entity(PortInstanceIdentifier),
        }
        methods {
            get_name -> ref str,
        }
    }

    entity TransitionGraph native fpp_analysis::semantics::state_machine::TransitionGraph {
        fields {
            initial_node: opt(entity(TransitionGraphNode)),
            arc_map: map(entity(TransitionGraphNode), list(union(TransitionGraphArc))),
        }
        methods {
            add_arc(arc: union(TransitionGraphArc)) -> entity(TransitionGraph),
            add_node(node: entity(TransitionGraphNode)) -> entity(TransitionGraph),
            add_reverse_arc(arc: union(TransitionGraphArc)) -> entity(TransitionGraph),
            get_reverse_graph -> entity(TransitionGraph),
        }
    }

    entity TransitionGraphNode native fpp_analysis::semantics::transition_graph::Node {
        fields {
            soc: union(StateOrChoice),
        }
    }

    leaf_enum Direction native fpp_analysis::semantics::Direction {
        Input: unit,
        Output: unit,
    }

    leaf_enum IntegerFormatKind native fpp_analysis::semantics::IntegerFormatKind {
        Character: unit,
        Decimal: unit,
        Hexadecimal: unit,
        Octal: unit,
    }

    leaf_enum Kind native fpp_analysis::semantics::Kind {
        External: unit,
        Internal: unit,
    }

    leaf_enum ParamKind native fpp_analysis::semantics::ParamKind {
        Save: unit,
        Set: unit,
    }

    leaf_enum RationalFormatKind native fpp_analysis::semantics::RationalFormatKind {
        Exponent: unit,
        Fixed: unit,
        General: unit,
    }

}
