//! Compile-time-expanded semantic-layer bindings.
//!
//! [`defs`] is the checked-in declaration file — a mechanical 1:1 mirror of the
//! `fpp_analysis` semantic layer rooted at `Analysis`, generated by
//! `cargo run -p fpp_python_bindgen`. The
//! `fpp_python_macros::fpp_sem_bindings!` invocation inside it expands, at
//! compile time, into the read-only PyO3 wrappers for the whole semantic graph:
//! the `Analysis` root, every closed union (`Symbol`/`Type`/`Value` + the
//! state-machine/port unions) as a base class carrying its variants as nested
//! classes, with its `*Ref`/`*Arg` newtypes, every entity (including opaque
//! handles), the payload structs, and the leaf-enum mirrors — plus
//! `defs::register`, `defs::union_stubs` and `defs::PY_MODULE`.
//!
//! These wrappers are the package itself ([`PY_MODULE`]); the AST wrappers are the
//! `ast` submodule ([`crate::ast::PY_MODULE`]). That is what lets `Connection`,
//! `PortInstanceIdentifier` and `TlmChannelIdentifier` name the semantic entity here
//! and the grammar production there.
//!
//! [`hand`] holds the one thing the macro cannot produce mechanically:
//! `build_type` (the `Type` union is `custom_build` because an "unknown" type whose
//! def node is absent from the walk must render as the bare base). It re-exports
//! through `crate::sem::*` so callers reference stable paths.
//!
//! `__repr__` and `__str__` are NOT hand-written: every class gets
//! `<PythonClassName …>` from its `repr` directive, and `__str__` wherever the
//! native impls `Display` — see [`crate::sem::defs`]'s macro and the bindgen's
//! `repr_directive`.

mod defs;
mod hand;

// `defs` (generated): the `Analysis` root, every union + its `*Ref`/`*Arg`/`*_ref`/`build_*`
// items, the entities + `build_*`, payloads, leaf enums, and `defs::register` /
// `defs::union_stubs` (shadowed by the combined wrappers below).
pub use defs::*;
// The single surviving hand-build: the `Type` union is `custom_build`, so the
// generated `type_ref` calls `crate::sem::build_type`.
pub use hand::build_type;

/// Register every generated + hand-authored semantic pyclass with the module.
pub fn register(m: &::pyo3::Bound<'_, ::pyo3::types::PyModule>) -> ::pyo3::PyResult<()> {
    defs::register(m)?;
    hand::register(m)?;
    Ok(())
}

/// One [`crate::UnionStub`] per generated closed union.
pub fn union_stubs() -> ::std::vec::Vec<crate::UnionStub> {
    defs::union_stubs()
}
