# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import fpp
import typing
import fpp.ast
__all__ = [
    "AstNode",
    "Binop",
    "ComponentKind",
    "Connection",
    "ConnectionPatternKind",
    "DefAbsType",
    "DefAction",
    "DefAliasType",
    "DefArray",
    "DefChoice",
    "DefComponent",
    "DefComponentInstance",
    "DefConstant",
    "DefEnum",
    "DefEnumConstant",
    "DefGuard",
    "DefInterface",
    "DefModule",
    "DefPort",
    "DefSignal",
    "DefState",
    "DefStateMachine",
    "DefStruct",
    "DefSystem",
    "DefTopology",
    "DoExpr",
    "EventSeverity",
    "EventThrottle",
    "Expr",
    "ExprKind",
    "FloatKind",
    "FormalParam",
    "FormalParamKind",
    "GeneralPortInstanceKind",
    "Ident",
    "InputPortKind",
    "IntegerKind",
    "LitString",
    "Opaque",
    "PortInstanceIdentifier",
    "Qualified",
    "QueueFull",
    "QueueFullSpecifier",
    "SpecCommand",
    "SpecContainer",
    "SpecDirectConnectionGraph",
    "SpecEvent",
    "SpecGeneralPortInstance",
    "SpecInclude",
    "SpecInit",
    "SpecInitialTransition",
    "SpecInstance",
    "SpecInterfaceImport",
    "SpecInternalPort",
    "SpecLoc",
    "SpecLocKind",
    "SpecParam",
    "SpecPatternConnectionGraph",
    "SpecPortMatching",
    "SpecRecord",
    "SpecSpecialPortInstance",
    "SpecStateEntry",
    "SpecStateExit",
    "SpecStateMachineInstance",
    "SpecStateTransition",
    "SpecTlmChannel",
    "SpecTlmPacket",
    "SpecTlmPacketSet",
    "SpecTopPort",
    "SpecialPortInstanceKind",
    "StructExprMember",
    "StructTypeMember",
    "TlmChannelIdentifier",
    "TlmChannelLimit",
    "TlmChannelLimitKind",
    "TlmChannelUpdate",
    "TransitionExpr",
    "TransitionOrDo",
    "TypeName",
    "TypeNameKind",
    "Unop",
]

class AstNode:
    r"""
    Base class for every AST-node wrapper: holds the `Model` handle + the
    node, and the getters common to all nodes. Node wrappers are
    `#[pyclass(extends = AstNode)]` unit subclasses.
    """
    @property
    def node_id(self) -> builtins.int: ...
    @property
    def location(self) -> fpp.Loc: ...
    @property
    def span(self) -> fpp.Span: ...
    @property
    def in_source(self) -> builtins.bool:
        r"""
        Whether this node belongs to a unit the caller asked about, rather
        than one passed to `analyze(imports=...)` to resolve references.
        """
    @property
    def children(self) -> builtins.list[AstNode]:
        r"""
        This node's direct child nodes, in source order.
        """
    @property
    def pre_annotation(self) -> builtins.list[builtins.str]: ...
    @property
    def post_annotation(self) -> builtins.list[builtins.str]: ...
    @property
    def definition(self) -> typing.Optional[fpp.Symbol.Variant]:
        r"""
        The definition this use-site node resolves to (or None).
        """
    @property
    def resolved_type(self) -> typing.Optional[fpp.Type.Variant]:
        r"""
        The resolved type of this node (or None).
        """
    @property
    def resolved_value(self) -> typing.Optional[fpp.Value.Variant]:
        r"""
        The resolved (constant-folded) value of this node (or None).
        """

@typing.final
class Connection(AstNode):
    @property
    def is_unmatched(self) -> builtins.bool: ...
    @property
    def from_port(self) -> PortInstanceIdentifier: ...
    @property
    def from_index(self) -> typing.Optional[Expr]: ...
    @property
    def to_port(self) -> PortInstanceIdentifier: ...
    @property
    def to_index(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefAbsType(AstNode):
    @property
    def name(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefAction(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefAliasType(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefArray(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> Expr: ...
    @property
    def elt_type(self) -> TypeName: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefChoice(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def guard(self) -> Ident: ...
    @property
    def if_transition(self) -> TransitionExpr: ...
    @property
    def else_transition(self) -> TransitionExpr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefComponent(AstNode):
    @property
    def kind(self) -> ComponentKind: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefAbsType | DefAliasType | DefArray | DefConstant | DefEnum | DefStateMachine | DefStruct | SpecCommand | SpecContainer | SpecEvent | SpecGeneralPortInstance | SpecInclude | SpecInterfaceImport | SpecInternalPort | SpecParam | SpecPortMatching | SpecRecord | SpecSpecialPortInstance | SpecStateMachineInstance | SpecTlmChannel]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefComponentInstance(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def component(self) -> Ident | Qualified: ...
    @property
    def base_id(self) -> typing.Optional[Expr]: ...
    @property
    def impl_type(self) -> typing.Optional[builtins.str]: ...
    @property
    def file(self) -> typing.Optional[builtins.str]: ...
    @property
    def queue_size(self) -> typing.Optional[Expr]: ...
    @property
    def stack_size(self) -> typing.Optional[Expr]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def cpu(self) -> typing.Optional[Expr]: ...
    @property
    def init_specs(self) -> builtins.list[SpecInit]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefConstant(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> Expr: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefEnum(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    @property
    def constants(self) -> builtins.list[DefEnumConstant]: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefEnumConstant(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefGuard(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefInterface(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecGeneralPortInstance | SpecInterfaceImport | SpecSpecialPortInstance]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefModule(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefAbsType | DefAliasType | DefArray | DefComponent | DefComponentInstance | DefConstant | DefEnum | DefInterface | DefModule | DefPort | DefStateMachine | DefStruct | DefSystem | DefTopology | SpecInclude | SpecLoc]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def return_type(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefSignal(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> typing.Optional[TypeName]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefState(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[DefChoice | DefState | SpecInclude | SpecInitialTransition | SpecStateEntry | SpecStateExit | SpecStateTransition]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefStateMachine(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> typing.Optional[builtins.list[DefAbsType | DefAction | DefAliasType | DefArray | DefChoice | DefConstant | DefEnum | DefGuard | DefSignal | DefState | DefStruct | SpecInclude | SpecInitialTransition]]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefStruct(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[StructTypeMember]: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefSystem(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def topology(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DefTopology(AstNode):
    @property
    def is_deployment(self) -> builtins.bool: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecDirectConnectionGraph | SpecInclude | SpecInstance | SpecPatternConnectionGraph | SpecTlmPacketSet | SpecTopPort]: ...
    @property
    def implements(self) -> builtins.list[Ident | Qualified]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DoExpr(AstNode):
    @property
    def actions(self) -> builtins.list[Ident]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EventThrottle(AstNode):
    @property
    def count(self) -> Expr: ...
    @property
    def every(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Expr(AstNode):
    @property
    def kind(self) -> ExprKind.Variant: ...
    def __repr__(self) -> builtins.str: ...

class ExprKind:
    Variant: typing.TypeAlias = ExprKind.Array | ExprKind.ArraySubscript | ExprKind.Binop | ExprKind.Dot | ExprKind.Ident | ExprKind.LiteralBool | ExprKind.LiteralInt | ExprKind.LiteralFloat | ExprKind.LiteralString | ExprKind.Paren | ExprKind.SizeOf | ExprKind.Struct | ExprKind.Unop
    @typing.final
    class Array(ExprKind):
        @property
        def elements(self) -> builtins.list[Expr]: ...

    @typing.final
    class ArraySubscript(ExprKind):
        @property
        def e1(self) -> Expr: ...
        @property
        def e2(self) -> Expr: ...

    @typing.final
    class Binop(ExprKind):
        @property
        def left(self) -> Expr: ...
        @property
        def op(self) -> fpp.ast.Binop: ...
        @property
        def right(self) -> Expr: ...

    @typing.final
    class Dot(ExprKind):
        @property
        def e(self) -> Expr: ...
        @property
        def id(self) -> fpp.ast.Ident: ...

    @typing.final
    class Ident(ExprKind):
        @property
        def value(self) -> builtins.str: ...

    @typing.final
    class LiteralBool(ExprKind):
        @property
        def value(self) -> builtins.bool: ...

    @typing.final
    class LiteralInt(ExprKind):
        @property
        def value(self) -> builtins.str: ...

    @typing.final
    class LiteralFloat(ExprKind):
        @property
        def value(self) -> builtins.str: ...

    @typing.final
    class LiteralString(ExprKind):
        @property
        def value(self) -> builtins.str: ...

    @typing.final
    class Paren(ExprKind):
        @property
        def value(self) -> Expr: ...

    @typing.final
    class SizeOf(ExprKind):
        @property
        def value(self) -> TypeName: ...

    @typing.final
    class Struct(ExprKind):
        @property
        def elements(self) -> builtins.list[StructExprMember]: ...

    @typing.final
    class Unop(ExprKind):
        @property
        def op(self) -> fpp.ast.Unop: ...
        @property
        def e(self) -> Expr: ...


@typing.final
class FormalParam(AstNode):
    @property
    def kind(self) -> FormalParamKind: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Ident(AstNode):
    @property
    def data(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class LitString(AstNode):
    @property
    def data(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Opaque(AstNode):
    @property
    def kind(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PortInstanceIdentifier(AstNode):
    @property
    def interface_instance(self) -> Ident | Qualified: ...
    @property
    def port_name(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Qualified(AstNode):
    @property
    def qualifier(self) -> Ident | Qualified: ...
    @property
    def name(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class QueueFullSpecifier(AstNode):
    @property
    def kind(self) -> QueueFull: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecCommand(AstNode):
    @property
    def kind(self) -> InputPortKind: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def opcode(self) -> typing.Optional[Expr]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecContainer(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def default_priority(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecDirectConnectionGraph(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def connections(self) -> builtins.list[Connection]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecEvent(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def severity(self) -> EventSeverity: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def format(self) -> builtins.str: ...
    @property
    def throttle(self) -> typing.Optional[EventThrottle]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecGeneralPortInstance(AstNode):
    @property
    def kind(self) -> GeneralPortInstanceKind: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> typing.Optional[Expr]: ...
    @property
    def port(self) -> typing.Optional[Ident | Qualified]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInclude(AstNode):
    @property
    def file(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInit(AstNode):
    @property
    def phase(self) -> Expr: ...
    @property
    def code(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInitialTransition(AstNode):
    @property
    def transition(self) -> TransitionExpr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInstance(AstNode):
    @property
    def instance(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInterfaceImport(AstNode):
    @property
    def interface(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecInternalPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def params(self) -> builtins.list[FormalParam]: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[QueueFull]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecLoc(AstNode):
    @property
    def kind(self) -> SpecLocKind: ...
    @property
    def symbol(self) -> Ident | Qualified: ...
    @property
    def file(self) -> builtins.str: ...
    @property
    def is_dictionary_def(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecParam(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def default(self) -> typing.Optional[Expr]: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def set_opcode(self) -> typing.Optional[Expr]: ...
    @property
    def save_opcode(self) -> typing.Optional[Expr]: ...
    @property
    def is_external(self) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecPatternConnectionGraph(AstNode):
    @property
    def kind(self) -> ConnectionPatternKind: ...
    @property
    def source(self) -> Ident | Qualified: ...
    @property
    def targets(self) -> builtins.list[Ident | Qualified]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecPortMatching(AstNode):
    @property
    def port1(self) -> Ident: ...
    @property
    def port2(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecRecord(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def record_type(self) -> TypeName: ...
    @property
    def is_array(self) -> builtins.bool: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecSpecialPortInstance(AstNode):
    @property
    def input_kind(self) -> typing.Optional[InputPortKind]: ...
    @property
    def kind(self) -> SpecialPortInstanceKind: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecStateEntry(AstNode):
    @property
    def actions(self) -> DoExpr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecStateExit(AstNode):
    @property
    def actions(self) -> DoExpr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecStateMachineInstance(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def state_machine(self) -> Ident | Qualified: ...
    @property
    def priority(self) -> typing.Optional[Expr]: ...
    @property
    def queue_full(self) -> typing.Optional[QueueFull]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecStateTransition(AstNode):
    @property
    def signal(self) -> Ident: ...
    @property
    def guard(self) -> typing.Optional[Ident]: ...
    @property
    def transition_or_do(self) -> TransitionOrDo.Variant: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecTlmChannel(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def update(self) -> typing.Optional[TlmChannelUpdate]: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    @property
    def low(self) -> builtins.list[TlmChannelLimit]: ...
    @property
    def high(self) -> builtins.list[TlmChannelLimit]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecTlmPacket(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def id(self) -> typing.Optional[Expr]: ...
    @property
    def group(self) -> Expr: ...
    @property
    def members(self) -> builtins.list[SpecInclude | TlmChannelIdentifier]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecTlmPacketSet(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def members(self) -> builtins.list[SpecInclude | SpecTlmPacket]: ...
    @property
    def omitted(self) -> builtins.list[TlmChannelIdentifier]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpecTopPort(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def underlying_port(self) -> PortInstanceIdentifier: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class StructExprMember(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def value(self) -> Expr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class StructTypeMember(AstNode):
    @property
    def name(self) -> builtins.str: ...
    @property
    def size(self) -> typing.Optional[Expr]: ...
    @property
    def type_name(self) -> TypeName: ...
    @property
    def format(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TlmChannelIdentifier(AstNode):
    @property
    def component_instance(self) -> Ident | Qualified: ...
    @property
    def channel_name(self) -> Ident: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TlmChannelLimit(AstNode):
    @property
    def kind(self) -> TlmChannelLimitKind: ...
    @property
    def value(self) -> Expr: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TransitionExpr(AstNode):
    @property
    def actions(self) -> typing.Optional[DoExpr]: ...
    @property
    def target(self) -> Ident | Qualified: ...
    def __repr__(self) -> builtins.str: ...

class TransitionOrDo:
    Variant: typing.TypeAlias = TransitionOrDo.Transition | TransitionOrDo.Do
    @typing.final
    class Transition(TransitionOrDo):
        @property
        def value(self) -> TransitionExpr: ...

    @typing.final
    class Do(TransitionOrDo):
        @property
        def value(self) -> DoExpr: ...


@typing.final
class TypeName(AstNode):
    @property
    def kind(self) -> TypeNameKind.Variant: ...
    def __repr__(self) -> builtins.str: ...

class TypeNameKind:
    Variant: typing.TypeAlias = TypeNameKind.Bool | TypeNameKind.Floating | TypeNameKind.Integer | TypeNameKind.QualIdent | TypeNameKind.String
    @typing.final
    class Bool(TypeNameKind):
        ...

    @typing.final
    class Floating(TypeNameKind):
        @property
        def value(self) -> FloatKind: ...

    @typing.final
    class Integer(TypeNameKind):
        @property
        def value(self) -> IntegerKind: ...

    @typing.final
    class QualIdent(TypeNameKind):
        @property
        def value(self) -> Ident | Qualified: ...

    @typing.final
    class String(TypeNameKind):
        @property
        def value(self) -> typing.Optional[Expr]: ...


@typing.final
class Binop:
    r"""
    A closed set of `Binop` kinds.
    """
    Add: typing.ClassVar[Binop]
    Div: typing.ClassVar[Binop]
    Mul: typing.ClassVar[Binop]
    Sub: typing.ClassVar[Binop]
    LShift: typing.ClassVar[Binop]
    RShift: typing.ClassVar[Binop]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class ComponentKind:
    r"""
    A closed set of `ComponentKind` kinds.
    """
    Active: typing.ClassVar[ComponentKind]
    Passive: typing.ClassVar[ComponentKind]
    Queued: typing.ClassVar[ComponentKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class ConnectionPatternKind:
    r"""
    A closed set of `ConnectionPatternKind` kinds.
    """
    Command: typing.ClassVar[ConnectionPatternKind]
    Event: typing.ClassVar[ConnectionPatternKind]
    Health: typing.ClassVar[ConnectionPatternKind]
    Param: typing.ClassVar[ConnectionPatternKind]
    Telemetry: typing.ClassVar[ConnectionPatternKind]
    TextEvent: typing.ClassVar[ConnectionPatternKind]
    Time: typing.ClassVar[ConnectionPatternKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class EventSeverity:
    r"""
    A closed set of `EventSeverity` kinds.
    """
    ActivityHigh: typing.ClassVar[EventSeverity]
    ActivityLow: typing.ClassVar[EventSeverity]
    Command: typing.ClassVar[EventSeverity]
    Diagnostic: typing.ClassVar[EventSeverity]
    Fatal: typing.ClassVar[EventSeverity]
    WarningHigh: typing.ClassVar[EventSeverity]
    WarningLow: typing.ClassVar[EventSeverity]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class FloatKind:
    r"""
    A closed set of `FloatKind` kinds.
    """
    F32: typing.ClassVar[FloatKind]
    F64: typing.ClassVar[FloatKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class FormalParamKind:
    r"""
    A closed set of `FormalParamKind` kinds.
    """
    Ref: typing.ClassVar[FormalParamKind]
    Value: typing.ClassVar[FormalParamKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class GeneralPortInstanceKind:
    r"""
    A closed set of `GeneralPortInstanceKind` kinds.
    """
    Input: typing.ClassVar[GeneralPortInstanceKind]
    Output: typing.ClassVar[GeneralPortInstanceKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class InputPortKind:
    r"""
    A closed set of `InputPortKind` kinds.
    """
    Async: typing.ClassVar[InputPortKind]
    Guarded: typing.ClassVar[InputPortKind]
    Sync: typing.ClassVar[InputPortKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class IntegerKind:
    r"""
    A closed set of `IntegerKind` kinds.
    """
    U8: typing.ClassVar[IntegerKind]
    I8: typing.ClassVar[IntegerKind]
    U16: typing.ClassVar[IntegerKind]
    I16: typing.ClassVar[IntegerKind]
    U32: typing.ClassVar[IntegerKind]
    I32: typing.ClassVar[IntegerKind]
    U64: typing.ClassVar[IntegerKind]
    I64: typing.ClassVar[IntegerKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class QueueFull:
    r"""
    A closed set of `QueueFull` kinds.
    """
    Assert: typing.ClassVar[QueueFull]
    Block: typing.ClassVar[QueueFull]
    Drop: typing.ClassVar[QueueFull]
    Hook: typing.ClassVar[QueueFull]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class SpecLocKind:
    r"""
    A closed set of `SpecLocKind` kinds.
    """
    Component: typing.ClassVar[SpecLocKind]
    Instance: typing.ClassVar[SpecLocKind]
    Constant: typing.ClassVar[SpecLocKind]
    Port: typing.ClassVar[SpecLocKind]
    StateMachine: typing.ClassVar[SpecLocKind]
    System: typing.ClassVar[SpecLocKind]
    Type: typing.ClassVar[SpecLocKind]
    Interface: typing.ClassVar[SpecLocKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class SpecialPortInstanceKind:
    r"""
    A closed set of `SpecialPortInstanceKind` kinds.
    """
    CommandRecv: typing.ClassVar[SpecialPortInstanceKind]
    CommandReg: typing.ClassVar[SpecialPortInstanceKind]
    CommandResp: typing.ClassVar[SpecialPortInstanceKind]
    Event: typing.ClassVar[SpecialPortInstanceKind]
    ParamGet: typing.ClassVar[SpecialPortInstanceKind]
    ParamSet: typing.ClassVar[SpecialPortInstanceKind]
    ProductGet: typing.ClassVar[SpecialPortInstanceKind]
    ProductRecv: typing.ClassVar[SpecialPortInstanceKind]
    ProductRequest: typing.ClassVar[SpecialPortInstanceKind]
    ProductSend: typing.ClassVar[SpecialPortInstanceKind]
    Telemetry: typing.ClassVar[SpecialPortInstanceKind]
    TextEvent: typing.ClassVar[SpecialPortInstanceKind]
    TimeGet: typing.ClassVar[SpecialPortInstanceKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class TlmChannelLimitKind:
    r"""
    A closed set of `TlmChannelLimitKind` kinds.
    """
    Red: typing.ClassVar[TlmChannelLimitKind]
    Orange: typing.ClassVar[TlmChannelLimitKind]
    Yellow: typing.ClassVar[TlmChannelLimitKind]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class TlmChannelUpdate:
    r"""
    A closed set of `TlmChannelUpdate` kinds.
    """
    Always: typing.ClassVar[TlmChannelUpdate]
    OnChange: typing.ClassVar[TlmChannelUpdate]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

@typing.final
class Unop:
    r"""
    A closed set of `Unop` kinds.
    """
    Minus: typing.ClassVar[Unop]

    @property
    def name(self) -> builtins.str:
        r"""
        Get enum variant name as a string
        """
    @property
    def value(self) -> builtins.str:
        r"""
        The same string as `name` (`enum.StrEnum`).
        """

